sudo: false # Use new Travis container-based infrastructure
language: python
python: 2.7
cache: pip
addons:
  ssh_known_hosts: api.openfisca.fr
install:
  - pip install --upgrade pip wheel  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
  - pip install "OpenFisca-France==15.1.0"  # Needed only for tests.
  - pip install --editable .[test]
script: ./travis-run-tests.sh
before_deploy: ./travis-before-deploy.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: ./travis-release-tag.sh
    on:
      branch: ci
  - provider: pypi
    user: openfisca-bot
    password:
      secure: Ou0bDDMEsy08YkkD3soCjftZT6IqAGZQO7oE0iTJOY2jw4Zy+y5RHAyignSCnpvFZNVDc1+bG+BpwAaZ1bKqa0Be57ktK81bo/k4kf+OwCNT6Et2S4i4woLoDRwPjgMOn3/dmIE7H19wwuTQo4AB0WcdgMcBreyO+k4IvcYzQjU=
    distributions: "bdist_wheel"
    on:
      tags: true
  - provider: script
    script: ssh deploy-api@api.openfisca.fr
    on:
      tags: true
