sudo: false # Use new Travis container-based infrastructure
language: python
python: 2.7
cache: pip
install:
  - pip install --upgrade pip wheel  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
  - pip install --editable .[test]
script: nosetests
